### PR TITLE
show actual CELO balance

### PR DESCRIPTION
**Pull request by superbow1**
Added functionality to show users balance in DApp. I think this may be handy in some cases

### CODE REVIEW

**Comment by critesjosh** [comment]
Thanks for the PR! I like the idea, I think the UI could be cleaned up a bit. It looks pretty wonky a mobile device as it is.

Screen Shot 2022-04-01 at 2 22 57 PM

Maybe truncate the balance so it shows only 2 decimal place so the chip is smaller. And/or update the account chip so when you click on it, it shows additional information like the network details and account balance. Or maybe even add an "Account" tab similar to the "Storage" and "Greeter" tabs, but that shows account details. I am also open to suggestions.

**Comment by superbow1** [comment]
> Thanks for the PR! I like the idea, I think the UI could be cleaned up a bit. It looks pretty wonky a mobile device as it is.
> 
> Screen Shot 2022-04-01 at 2 22 57 PM
> 
> Maybe truncate the balance so it shows only 2 decimal place so the chip is smaller. And/or update the account chip so when you click on it, it shows additional information like the network details and account balance. Or maybe even add an "Account" tab similar to the "Storage" and "Greeter" tabs, but that shows account details. I am also open to suggestions.

Adding "Account" tab is a good idea, I will update my PR

**Comment by critesjosh** [comment]
Cool! Since there a bunch more space now, it might be cool to add cUSD and cEUR balances as well. wdyt?

Also, I am going to shorten the tab names because currently only 2 will appear on a mobile device at a time.

**Comment by superbow1** [comment]
> Cool! Since there a bunch more space now, it might be cool to add cUSD and cEUR balances as well. wdyt?
> 
> Also, I am going to shorten the tab names because currently only 2 will appear on a mobile device at a time.

Added cEUR and cUSD

**Comment by superbow1** [comment]
> Also, I am going to shorten the tab names because currently only 2 will appear on a mobile device at a time.

I think it is better to make tabs scrollable. It just needs few additional props

https://user-images.githubusercontent.com/102758523/161336509-fbdd79be-ff45-466e-8cd6-05db5dabf543.mp4

**Comment by critesjosh** [comment]
looks great, thanks!

**Pull request merged**
