### PR TITLE
extend balance page functionality

### PR DESCRIPTION
**Pull request by hpratt**
this adds the ability to toggle between base currencies on the balance page (ETH, USD, EUR, and CELO), see token balances denominated in the base currency, and see current price estimates for tokens in the base currency

### CODE REVIEW

**Comment by critesjosh** [comment]
I like the direction this going, but the UI looks pretty cluttered now. Maybe update the **Balance** section to be table or another format so it's easier to read. Also truncating all of the numbers to two decimal places would help. 

Screen Shot 2022-04-11 at 3 49 30 PM

**Comment by critesjosh** [comment]
I like the direction this going, but the UI looks pretty cluttered now. Maybe update the **Balance** section to be table or another format so it's easier to read. Also truncating all of the numbers to two decimal places would help. 

Screen Shot 2022-04-11 at 3 49 30 PM

**Comment by hpratt** [comment]
sure! how does this look
Screenshot from 2022-04-11 23-31-39
?

**Review by critesjosh — APPROVED** [review]
👍

**Comment by critesjosh** [comment]
looks great!

**Pull request merged**
