### PR TITLE
added basic redux scaffolding

### PR DESCRIPTION
**Pull request by superbow1**
All more or less complex DApps have state. So I think it will be very useful for future developers to already have boilerplate code for state management. As a small example of use case I've also added simple network block number indicator. 

P.S. @critesjosh since I've already submitted PR to gitcoin and I can't submit more than once, I'll just leave my address `0x8f57C541FCab6EED923988525d32a21694e911F1`

Thank you!

### CODE REVIEW

**Review by superbow1 — COMMENTED** [review]
`add react-transition-group import` is not really relevant since it loaded anyway by `mui`, added just  for clarity

**Review by critesjosh — APPROVED** [review]
cool! 👍

**Comment by critesjosh** [comment]
great addition! I love the block poller. how much time did this take you (roughly)?

**Comment by critesjosh** [comment]
im not seeing the block number on the mobile preview. Are you seeing it on your side?

**Comment by superbow1** [comment]
> im not seeing the block number on the mobile preview. Are you seeing it on your side?

Yes, it should show it on mobile. Have you connected the wallet? It will not show poller without a wallet since it uses contractkit

image

**Comment by superbow1** [comment]
Here is firefox screenshot

image

Haven't tested it on chrome though, will see if it makes a difference

**Comment by superbow1** [comment]
> great addition! I love the block poller. how much time did this take you (roughly)?

Around 4-6 hours

**Comment by critesjosh** [comment]
> https://deploy-preview-34--celo-progressive-dapp-starter.netlify.app/

yea, I don't see it when I test on my physical mobile device, connecting via "Valora". I also notice that it doesn't show up if I connect the desktop site to Alfajores Valora via WalletConnect. Perhaps this is an issue with use-contractkit?

**Comment by superbow1** [comment]
> > Yes, it should show it on mobile. Have you connected the wallet? It will not show poller without a wallet since it uses contractkit
> 
> yea, I don't see it when I test on my physical mobile device, connecting via "Valora". I also notice that it doesn't show up if I connect the desktop site to Alfajores Valora via WalletConnect. Perhaps this is an issue with use-contractkit?

Yep, just tried it with Celo Wallet - looks like newBlockHeaders subscription is not implemented. I can fix it: just replace it with 10 seconds timer and simple getBlock

**Comment by superbow1** [comment]
Looks better now!

**Comment by critesjosh** [comment]
https://explorer.celo.org/tx/0xbe5a87e82e34986553b6c529ee2e8060c4e40a26b0f64cf501ce868ff49d2ec9/token-transfers

**Comment by superbow1** [comment]
> https://explorer.celo.org/tx/0xbe5a87e82e34986553b6c529ee2e8060c4e40a26b0f64cf501ce868ff49d2ec9/token-transfers

Thank you!

**Pull request merged**
